# ./roles/redis/tasks/Archlinux.yml
- name: Install Redis server
  pacman:
    name: redis
    state: present

- name: Ensure Redis service is running
  service:
    name: redis
    state: started
    enabled: yes
