- name: Localhost Test
  hosts: localhost
  become: yes
  tasks:
    - name: Create server
      include_role:
        name: redis
      vars:
        server_images:
          - registry.access.redhat.com/ubi8/ubi:latest

    - name: Create clients
      include_role:
        name: redis
      vars:
        client_images:
          - ubuntu:latest
          - mcr.microsoft.com/windows/servercore:ltsc2019
