---
# ./roles/docker/tasks/RedHat.yml
- name: Install required packages
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present

- name: Add Docker repository
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/{{ ansible_distribution|lower }}/$basearch/stable
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg

- name: Install Docker
  yum:
    name: docker-ce
    state: present
