---
# ./roles/docker/tasks/Windows.yml
- name: Install Chocolatey
  win_shell: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
  args:
    creates: C:\ProgramData\chocolatey\bin\choco.exe

- name: Install Docker Desktop
  win_chocolatey:
    name: docker-desktop
    state: present
